### ISSUE TITLE
How to display a column with arrays?

### ISSUE THREAD

**Issue by arnonrdp** [dockerlead/vue-excel-xlsx#1]
First of all, I want to say that I have been using this tool a lot and I love how easy it is to use.

However, today I faced some data that is coming inside arrays. And the goal is to display each array item in one row, but all in the same cell. Here some mocked data:
```js
data() {
  return {
    columns: [
      { label: "Name", field: "name" },
      { label: "Age", field: "age" },
      { label: "Cars", field: "cars" },
    ],
    data: [
      { name: "John", age: 30, cars: ["Ford", "BMW", "Fiat"] },
      { name: "Jane", age: 32, cars: ["Fiat", "VW"] },
    ],
  };
},
```

So to solve this problem I did the following:
```js
mounted() {
  this.newData = this.data.map((item) => {
    return {
      ...item,
      cars: item.cars.join("\r\n"),
    };
  });
  console.log(this.newData);
},
```

However, despite working, it generates a damn hexadecimal. If I remove the `\r` the hexadecimal disappears, but Excel doesn't do the line break. I've also tried `<br/>`, which Excel just ignores.

Is there anything I can do to resolve this issue?

[filename.xlsx](https://github.com/dockerlead/vue-excel-xlsx/files/7856595/filename.xlsx)

**Comment by orendavisdev** [comment]
@ihsaneddin do you have any idea?

**Comment by arnonrdp** [comment]
I solved using another library.
